### ISSUE TITLE
Feature request: allow inserting the date in the log filename

### ISSUE THREAD

**Issue by koldLight** [ryapric/loggit#15]
Thanks for this simple and great package.

A common need is to register logs in different files by date. E.g. by day:

```
loggit-2021-03-10.log
loggit-2021-03-11.log
loggit-2021-03-12.log
...
```

It would be useful if the `set_logfile` function allowed inserting date variables, e.g.:

```
set_logfile(logfile = 'loggit-%Y-%m-%d.log')
```

And automatically creates and logs to the file depending on the current date.

I'm available for a pull request if you consider adding this feature into the package.

**Comment by ryapric** [comment]
Thanks @koldLight!
However, you can already get what you want with a `paste0()` collapse to `set_logfile()`, e.g.:

```
> loggit::set_logfile(paste0('loggit-', Sys.Date(), '.log'))
[1] "Log file set to loggit-2021-03-24.log"
```

I'd rather not add dynamic abstraction functionality for something that is (ideally) only called once per run, and written once per codebase. Unless I misunderstood?

**Comment by koldLight** [comment]
Yes, thanks for your comment, it think I was a bit biased by my use case.

I was thinking in "always up" applications (specifically, a [plumber API](https://www.rplumber.io/)), more than in batch scripts or analysis. In that cases, if you use the:

```
set_logfile(paste0('loggit-', Sys.Date(), '.log'))
```

I understand this will cause to have only one log file with the date the API was started, instead of daily log files. At least if I don't periodically force this `set_logfile` (when a new API request occurs or something like that).

I know, this is a bit specific to long running applications, such as APIs.

**Comment by ryapric** [comment]
(wooo late reply)

Yeah, for long-running applications like APIs, orchestrators, etc. etc., you could loop logic to just run the same `set_logfile()` call at the start of an event loop; that way, it would still make your log file names dynamic, without any extra effort.
