### ISSUE TITLE
Warnings if log_msg has more than one attribute

### ISSUE THREAD

**Issue by denrou** [ryapric/loggit#2]
First of all, thank you for this package!

Now, for the problem I encounter:

```R
library(loggit)
library(glue)

loggit("INFO", "First message")
loggit("INFO", "Second message")
# Warning message:
# In bind_rows_(x, .id) :
#   Vectorizing 'glue' elements may not preserve their attributes
```

This warning pops up because of `bind_rows` because `glue::glue` gives an object of class `glue` which is not present in the column of the dataframe.

I see two solutions to overcome this:

+ Use `as.character(log_msg)` to automatically convert every log message (and log details) into character
+ Use `suppressWarnings(dplyr::bind_rows(...))` to avoid this type of warning.

Note that I expect this kind of warning to happen not just with `glue` but for all objects with other attributes than `character` (`dates`, `durations`, ...)

**Comment by ryapric** [comment]
Hi Denis, thanks for pointing that out. I'd much rather take the first option, as the latter would suppress *all* warnings, which is a little spooky.

I have added your suggestion to the latest Github version, v1.1.1

Thanks!
