### ISSUE TITLE
Enable explicit configuration to log to STDOUT

### ISSUE THREAD

**Issue by nihonjinrxs** [ryapric/loggit#3]
In many of our production contexts, we log, usually in JSON, to STDOUT (or in rare cases STDERR), and have external log collectors that capture logs across many services.

The [filename test in `configurations.R`](https://github.com/ryapric/loggit/blob/master/R/configurations.R#L28) seems to prevent me from doing what I'd normally do for this:
```{R}
# gives me a writeable file handler for the standard output stream
log_file <- file("stdout", "w")
```

I think it would be helpful to allow for these basic streams as output.

This is also in concert with the [logging factor of the 12-factor app](https://12factor.net/logs), which recommends:
> A twelve-factor app never concerns itself with routing or storage of its output stream. It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout.

**Comment by ryapric** [comment]
Thanks for sharing that link! `loggit` is, and will always, default to file-based logging, as it's not explicitly designed for the use cases intended for that methodology:

> The twelve-factor app is a methodology for building _**software-as-a-service apps**_ [...]

But I can certainly see if I can get STDOUT logging to work as you describe, as an option.

**Comment by nihonjinrxs** [comment]
Would be appreciated, since most apps out there these days are software-as-a-service, also known as web apps and web apis.

**Comment by ryapric** [comment]
Note to self: I added an `echo` argument some time ago, but it doesn't log the JSON to `stdout`, just a regular text log entry. Need to configure to log the JSON. Will need to make sure the escaped quotes in the JSON aren't present in `stdout`.

**Comment by ryapric** [comment]
Done, will appear in v2.0.0.
