### ISSUE TITLE
Timeline for implementation of in-package logging?

### ISSUE THREAD

**Issue by nihonjinrxs** [ryapric/loggit#5]
In your README, you note:
> If you really wish to have all exception messages logged by loggit, please be patient, as this feature is in the works.

I'm wondering about the timeline for implementation for this, as it's critical for me to be able to do that for this package to be useful for production work.

**Comment by ryapric** [comment]
Hi, thanks for checking in! This ended up proving to be quite a bit more difficult than anticipated; the plan was to re-compile all of the user's installed packages, with `loggit` exported in their namespace. However, it wasn't working as intended at the time. I'm happy to give it another go, if you think it would be useful.

Though, as you pointed out in #3, you'd personally prefer to log to STDOUT; are other packages' errors not captured in STDOUT already? I'm not as familiar with system logging.

**Comment by nihonjinrxs** [comment]
They are, but not as JSON.

**Comment by ryapric** [comment]
This was *super* ambitious at the time, and while it might still be *somehow possible*, I'm taking it off the table due to the sheer complexity and principle-violation of what a package should do to a userspace (i.e. editing a user's other installed packages).
